# Generated by 'ovhcloud cloud export-terraform'.
# Generate the matching configuration with:
#   terraform plan -generate-config-out=generated.tf

import {
  to = ovh_cloud_project_network_private.azertyuiop
  id = "f2ebcd175d4446029c09c3c8d009c44a/pn-1306287_3"
}

import {
  to = ovh_cloud_project_network_private.pn-rbx-a-08042026
  id = "f2ebcd175d4446029c09c3c8d009c44a/pn-1306287_1"
}

import {
  to = ovh_cloud_project_network_private.aqwzscde
  id = "f2ebcd175d4446029c09c3c8d009c44a/pn-1306287_0"
}

import {
  to = ovh_cloud_project_network_private.zreg
  id = "f2ebcd175d4446029c09c3c8d009c44a/pn-1306287_10"
}

import {
  to = ovh_cloud_project_network_private.my-network
  id = "f2ebcd175d4446029c09c3c8d009c44a/pn-1306287_1900"
}

import {
  to = ovh_cloud_project_network_private.pn-gra11-06052026
  id = "f2ebcd175d4446029c09c3c8d009c44a/pn-1306287_5"
}

import {
  to = ovh_cloud_project_network_private.pn-gra11-06052026_2
  id = "f2ebcd175d4446029c09c3c8d009c44a/pn-1306287_4"
}

import {
  to = ovh_cloud_project_network_private.cli-v2-net-renamed
  id = "f2ebcd175d4446029c09c3c8d009c44a/pn-1306287_42"
}

import {
  to = ovh_cloud_project_user.user-jmryyskhbqwj
  id = "f2ebcd175d4446029c09c3c8d009c44a/670887"
}

import {
  to = ovh_cloud_project_user.user-dts7jf3qfse2
  id = "f2ebcd175d4446029c09c3c8d009c44a/671110"
}

import {
  to = ovh_cloud_project_user.user-dxsg7rkaj33r
  id = "f2ebcd175d4446029c09c3c8d009c44a/671118"
}

import {
  to = ovh_cloud_project_user.user-dgnmty7dy2pe
  id = "f2ebcd175d4446029c09c3c8d009c44a/671677"
}

import {
  to = ovh_cloud_project_user.user-reycs2bbepcj
  id = "f2ebcd175d4446029c09c3c8d009c44a/671529"
}

import {
  to = ovh_cloud_project_user.user-uwgsnmmqmdgs
  id = "f2ebcd175d4446029c09c3c8d009c44a/671531"
}

import {
  to = ovh_cloud_project_user.user-qhmczfnvcdgv
  id = "f2ebcd175d4446029c09c3c8d009c44a/671559"
}

import {
  to = ovh_cloud_project_user.user-ptpj4nfcvzem
  id = "f2ebcd175d4446029c09c3c8d009c44a/671561"
}

import {
  to = ovh_cloud_project_user.user-utfy5vdhxq8z
  id = "f2ebcd175d4446029c09c3c8d009c44a/674807"
}

