name: 🛠️ Feature request
description: Ask for a new feature
title: "[Feature]: "
labels: ["Feature"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you want.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Product concerned
    description: Which product is this feature request for? (e.g., Cloud, VPS, Domains, etc.)
  validations:
    required: false
- type: textarea
  attributes:
    label: Feature description
    description: A concise description of the feature you want.
  validations:
    required: true
