name: Go

on: [push]

jobs:
  build:
    runs-on: library/go-1-24
    steps:
    - uses: actions/checkout
    - run: go get ./...
    - run: go test -v ./...
    - run: go build -v -o ovhcloud ./cmd/ovhcloud
    - uses: actions/uploadArtifact
      with:
        path: ovhcloud
        if-no-files-found: error

integrations: [artifactory-digital-core-platform-api]