// SPDX-FileCopyrightText: 2025 OVH SAS <opensource@ovh.net>
//
// SPDX-License-Identifier: Apache-2.0

package supporttickets

import (
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// listCommand rebuilds just enough of the list command to exercise the query
// builder: the boolean filters are read through cobra's Changed, so they cannot
// be tested from the spec alone.
func listCommand() *cobra.Command {
	ListSpec.Archived = false
	ListSpec.CustomerReplyNeeded = false
	ListSpec.ExcludeAutogenerated = false
	ListSpec.Category = ""
	ListSpec.MaxCreationDate = ""
	ListSpec.MinCreationDate = ""
	ListSpec.Product = ""
	ListSpec.ServiceName = ""
	ListSpec.Status = ""
	ListSpec.Subject = ""
	ListSpec.TicketNumber = ""

	cmd := &cobra.Command{Use: "list"}
	cmd.Flags().BoolVar(&ListSpec.Archived, "archived", false, "")
	cmd.Flags().BoolVar(&ListSpec.CustomerReplyNeeded, "needs-reply", false, "")
	cmd.Flags().BoolVar(&ListSpec.ExcludeAutogenerated, "exclude-autogenerated", false, "")
	return cmd
}

func TestNoFilterAsksForNoQuery(t *testing.T) {
	query, err := ticketListQuery(listCommand())
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}
	if query != "" {
		t.Fatalf("an unfiltered list must not carry a query, got %q", query)
	}
}

// The three booleans are meaningful in both positions, so a flag left alone
// cannot be encoded as false: that would invent a filter the operator never
// asked for, and quietly hide every archived ticket.
func TestABooleanIsOnlySentWhenItWasTyped(t *testing.T) {
	cmd := listCommand()
	if err := cmd.ParseFlags([]string{"--archived=false"}); err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	query, err := ticketListQuery(cmd)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}
	if !strings.Contains(query, "archived=false") {
		t.Fatalf("--archived=false is a filter, not a default; got %q", query)
	}
	if strings.Contains(query, "customerReplyNeeded") || strings.Contains(query, "excludeAutogenerated") {
		t.Fatalf("only the flag that was typed belongs in the query, got %q", query)
	}
}

func TestTypedFiltersReachTheQuery(t *testing.T) {
	cmd := listCommand()
	ListSpec.Status = "open"
	ListSpec.ServiceName = "ns1.example"
	ListSpec.Product = "dedicated"

	query, err := ticketListQuery(cmd)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}
	for _, want := range []string{"status=open", "serviceName=ns1.example", "product=dedicated"} {
		if !strings.Contains(query, want) {
			t.Fatalf("query %q is missing %q", query, want)
		}
	}
}

// A value the API would reject is rejected here, with the ones it accepts. The
// accepted list is read from the specification embedded in the binary, so this
// also proves the parameter enums are where the code looks for them.
func TestAnImpossibleStatusIsRefusedLocally(t *testing.T) {
	cmd := listCommand()
	ListSpec.Status = "pending"

	_, err := ticketListQuery(cmd)
	if err == nil {
		t.Fatal("a status outside the enum must not reach the API")
	}
	if !strings.Contains(err.Error(), "open") || !strings.Contains(err.Error(), "closed") {
		t.Fatalf("the refusal must name the accepted values, got %q", err)
	}
}

func TestTicketLabelNamesWhatTheOperatorRecognises(t *testing.T) {
	label := ticketLabel("15647305", map[string]any{
		"ticketNumber": 9876543,
		"subject":      "Disk replacement on ns1.example",
	})
	for _, want := range []string{"15647305", "9876543", "Disk replacement"} {
		if !strings.Contains(label, want) {
			t.Fatalf("label %q is missing %q", label, want)
		}
	}

	// A ticket the API answered with nothing but an identifier still has to be
	// nameable, or the confirmation prompt breaks on it.
	if bare := ticketLabel("42", map[string]any{}); bare != "42" {
		t.Fatalf("a bare ticket is named by its id, got %q", bare)
	}
}

// canBeClosed=false and "the API did not say" lead to different commands: one
// is a refusal the operator can act on, the other must not be turned into one.
func TestBoolFieldTellsFalseFromAbsent(t *testing.T) {
	if value, known := boolField(map[string]any{"canBeClosed": false}, "canBeClosed"); !known || value {
		t.Fatal("an explicit false is a known false")
	}
	if _, known := boolField(map[string]any{}, "canBeClosed"); known {
		t.Fatal("an absent field is not a false")
	}
	// The API decodes numbers as json.Number and booleans as bool, but a field
	// that ever came back as a string must not read as a silent false.
	if _, known := boolField(map[string]any{"canBeClosed": "false"}, "canBeClosed"); known {
		t.Fatal("a string is not a boolean")
	}
}
