// SPDX-FileCopyrightText: 2025 OVH SAS <opensource@ovh.net>
//
// SPDX-License-Identifier: Apache-2.0

package supporttickets

import (
	_ "embed"
	"fmt"
	"net/url"
	"strconv"
	"sync"

	"github.com/ovh/ovhcloud-cli/internal/assets"
	"github.com/ovh/ovhcloud-cli/internal/display"
	filtersLib "github.com/ovh/ovhcloud-cli/internal/filters"
	"github.com/ovh/ovhcloud-cli/internal/flags"
	httpLib "github.com/ovh/ovhcloud-cli/internal/http"
	"github.com/ovh/ovhcloud-cli/internal/openapi"
	"github.com/ovh/ovhcloud-cli/internal/services/common"
	"github.com/spf13/cobra"
)

var (
	supportticketsColumnsToDisplay = []string{"ticketId", "serviceName", "type", "category", "state"}
	messagesColumnsToDisplay       = []string{"messageId", "from", "creationDate", "body"}

	//go:embed templates/supporttickets.tmpl
	supportticketsTemplate string

	//go:embed parameter-samples/ticket-create.json
	TicketCreateExample string

	// ReplySpec holds the parameters for the reply command.
	ReplySpec struct {
		Body string `json:"body,omitempty"`
	}

	// ListSpec holds the filters GET /support/tickets applies itself. They are
	// worth exposing rather than leaving to --filter because the two work at
	// different ends of the wire: --filter drops rows the CLI has already
	// fetched, and this list is expanded one request per ticket.
	ListSpec struct {
		Archived             bool
		Category             string
		CustomerReplyNeeded  bool
		ExcludeAutogenerated bool
		MaxCreationDate      string
		MinCreationDate      string
		Product              string
		ServiceName          string
		Status               string
		Subject              string
		TicketNumber         string
	}

	// CreateSpec holds the parameters for the create command.
	CreateSpec struct {
		Body        string   `json:"body,omitempty"`
		Category    string   `json:"category,omitempty"`
		Impact      string   `json:"impact,omitempty"`
		Product     string   `json:"product,omitempty"`
		ServiceName string   `json:"serviceName,omitempty"`
		Subcategory string   `json:"subcategory,omitempty"`
		Subject     string   `json:"subject,omitempty"`
		Type        string   `json:"type,omitempty"`
		Urgency     string   `json:"urgency,omitempty"`
		Watchers    []string `json:"watchers,omitempty"`
	}
)

// The accepted values are read from the specification embedded in the binary
// rather than transcribed: `product` carries twenty-five today, and a list
// copied into Go drifts silently into a 400 the day the API gains a
// twenty-sixth.
var (
	ticketStatuses = sync.OnceValues(func() ([]string, error) {
		return openapi.GetParameterEnum(assets.SupportOpenapiSchema, "/support/tickets", "get", "status")
	})
	ticketCategories = sync.OnceValues(func() ([]string, error) {
		return openapi.GetParameterEnum(assets.SupportOpenapiSchema, "/support/tickets", "get", "category")
	})
	ticketProducts = sync.OnceValues(func() ([]string, error) {
		return openapi.GetParameterEnum(assets.SupportOpenapiSchema, "/support/tickets", "get", "product")
	})
)

// CompleteTicketStatus, CompleteTicketCategory and CompleteTicketProduct offer
// the accepted values on <tab>: the product list cannot fit in a flag help
// without making it unreadable.
func CompleteTicketStatus(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
	return common.CompleteEnum(ticketStatuses)
}

func CompleteTicketCategory(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
	return common.CompleteEnum(ticketCategories)
}

func CompleteTicketProduct(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
	return common.CompleteEnum(ticketProducts)
}

// ticketListQuery turns the filter flags into the query string the collection
// accepts, and rejects a value the API would reject.
//
// A boolean is only sent when it was typed. The three of them are meaningful in
// both positions — `archived=false` asks for the tickets that are not archived
// — so a flag left alone cannot be encoded as false without inventing a filter
// the operator did not ask for.
func ticketListQuery(cmd *cobra.Command) (string, error) {
	for _, check := range []struct {
		name  string
		value string
		read  func() ([]string, error)
	}{
		{"status", ListSpec.Status, ticketStatuses},
		{"category", ListSpec.Category, ticketCategories},
		{"product", ListSpec.Product, ticketProducts},
	} {
		if err := common.CheckEnumFlag(check.name, check.value, check.read); err != nil {
			return "", err
		}
	}

	values := url.Values{}
	for _, text := range []struct{ param, value string }{
		{"category", ListSpec.Category},
		{"maxCreationDate", ListSpec.MaxCreationDate},
		{"minCreationDate", ListSpec.MinCreationDate},
		{"product", ListSpec.Product},
		{"serviceName", ListSpec.ServiceName},
		{"status", ListSpec.Status},
		{"subject", ListSpec.Subject},
		{"ticketNumber", ListSpec.TicketNumber},
	} {
		if text.value != "" {
			values.Set(text.param, text.value)
		}
	}

	for _, flag := range []struct {
		param, name string
		value       bool
	}{
		{"archived", "archived", ListSpec.Archived},
		{"customerReplyNeeded", "needs-reply", ListSpec.CustomerReplyNeeded},
		{"excludeAutogenerated", "exclude-autogenerated", ListSpec.ExcludeAutogenerated},
	} {
		if cmd.Flags().Changed(flag.name) {
			values.Set(flag.param, strconv.FormatBool(flag.value))
		}
	}

	if len(values) == 0 {
		return "", nil
	}
	return "?" + values.Encode(), nil
}

func ListSupportTickets(cmd *cobra.Command, _ []string) {
	query, err := ticketListQuery(cmd)
	if err != nil {
		display.OutputError(&flags.OutputFormatConfig, "%s", err)
		return
	}

	ids, err := httpLib.FetchArray(TicketsPath+query, "")
	if err != nil {
		display.OutputError(&flags.OutputFormatConfig, "failed to fetch results: %s", err)
		return
	}

	// The query belongs to the collection call and to nothing else. The
	// expansion below builds one URL per ticket by appending to the path, so a
	// query string carried over would request
	// "/v1/support/tickets?status=open/12345" — a path the API cannot route,
	// for a filter that would look like it had worked.
	tickets, err := httpLib.FetchObjectsParallel[map[string]any](TicketsPath+"/%s", ids, flags.IgnoreErrors)
	if err != nil {
		display.OutputError(&flags.OutputFormatConfig, "failed to fetch tickets: %s", err)
		return
	}

	objects := make([]map[string]any, 0, len(tickets))
	for _, ticket := range tickets {
		// --ignore-errors leaves a hole rather than an entry.
		if ticket != nil {
			objects = append(objects, ticket)
		}
	}

	objects, err = filtersLib.FilterLines(objects, flags.GenericFilters)
	if err != nil {
		display.OutputError(&flags.OutputFormatConfig, "failed to filter results: %s", err)
		return
	}

	display.RenderTable(objects, supportticketsColumnsToDisplay, &flags.OutputFormatConfig)
}

func GetSupportTickets(_ *cobra.Command, args []string) {
	common.ManageObjectRequest(TicketsPath, args[0], supportticketsTemplate)
}

func ListSupportTicketMessages(_ *cobra.Command, args []string) {
	endpoint := fmt.Sprintf("%s/%s/messages", TicketsPath, url.PathEscape(args[0]))
	common.ManageListRequestNoExpand(endpoint, messagesColumnsToDisplay, flags.GenericFilters)
}

func ReplySupportTicket(_ *cobra.Command, args []string) {
	endpoint := fmt.Sprintf("%s/%s/reply", TicketsPath, url.PathEscape(args[0]))

	if err := httpLib.Client.Post(endpoint, ReplySpec, nil); err != nil {
		display.OutputError(&flags.OutputFormatConfig, "failed to reply to ticket: %s", err)
		return
	}

	display.OutputInfo(&flags.OutputFormatConfig, nil, "✅ Reply sent successfully")
}

func CreateSupportTicket(cmd *cobra.Command, _ []string) {
	createdResource, err := common.CreateResource(
		cmd,
		"/support/tickets/create",
		"/v1/support/tickets/create",
		TicketCreateExample,
		CreateSpec,
		assets.SupportOpenapiSchema,
		[]string{"body", "subject"})
	if err != nil {
		display.OutputError(&flags.OutputFormatConfig, "failed to create ticket: %s", err)
		return
	}

	ticketID, hasID := createdResource["ticketId"]
	hasID = hasID && ticketID != nil
	ticketNumber, hasNumber := createdResource["ticketNumber"]
	hasNumber = hasNumber && ticketNumber != nil
	switch {
	case hasID && hasNumber:
		display.OutputInfo(&flags.OutputFormatConfig, nil, "✅ Ticket %v (number %v) created successfully", ticketID, ticketNumber)
	case hasID:
		display.OutputInfo(&flags.OutputFormatConfig, nil, "✅ Ticket %v created successfully", ticketID)
	default:
		display.OutputInfo(&flags.OutputFormatConfig, nil, "✅ Ticket created successfully")
	}
}
